### ISSUE TITLE
Can't find ImageMagick on your server

### ISSUE THREAD

**Issue by tyssen** [electricputty/Thumber#14]
I had this working on a production server a while back but checking in on the site again recently I noticed the thumbnails are no longer appearing and in debug I get *Can't find ImageMagick on your server*. For at least one PDF, there's still a thumb stored on the server but it doesn't display. 

PHPInfo says ImageMagick 6.4.8 2010-02-20 Q16 is installed and enabled with module version 3.1.2.

I'm guessing some other configuration change on the server is the cause of the problem. Any idea what sort of things might be at fault?

**Comment by electricputty** [comment]
Hi,

There is a default property for the convert_bin. This may be different in your new environment,

```
private $convert_bin = 'convert';
```

You can over-ride this in your EE config using this syntax:

```
$config['thumber_convert_bin'] = "new-location";
```

Hope this helps.

Thanks,
Malcolm

**Comment by tyssen** [comment]
Got it. All good now, thanks.

**Comment by tyssen** [comment]
Actually, maybe not solved after all. The client has added a new PDF and no thumbnail is being generated. Looking through debugging output, the only thing I notice is `**Thumber** Current allocation mode is local`.

**Comment by electricputty** [comment]
Hi Tyssen,

This is a GhostScript error: https://en.wikipedia.org/wiki/Ghostscript

I did a quick Google and found some references to issues with specific PDFs or the installation of GhostScript itself.

If you get this error on every PDF you try to convert you might need to raise a ticket with your hosting provider to check GhostScript is running correctly.

Thanks,
Malcolm

**Comment by fantasticmachine** [comment]
I ran into something similar to this just this morning. My GS and Convert binaries are installed via Homebrew so I needed to set the path via the config file but the plug in doesn't seem to pick up those settings from the config array.

I haven't yet had time to dig into it (I just hardcoded the paths directly into the plugin) and it *could* be something to do with the way the multi-environment config is set up on this project but it's probably a simple enough fix.

**Comment by tyssen** [comment]
I checked with the hosting providers and they've confirmed that GS is installed and asked that I check that the path to run it is `/usr/bin/gs` which it looks like it already is.

**Comment by electricputty** [comment]
Hi Tyssen,

Can you confirm this error occurs on _all_ PDFs and is not limited to a one (or a few). There are known issues with GhostScript and some PDFs.

Also, can you let me know the version of GhostScript you are using?

Thanks,
Malcolm

**Comment by tyssen** [comment]
Yeah, you're right, it does seem to be working for some but not others. Oh well, will have to resort to manual methods for the ones that don't work.

**Comment by thisisjamessmith** [comment]
Hiya, I'm getting this error too locally on MAMP Pro, and tried all the suggested fixes to no avail.

Out of curiosity I simple changed this lib_check to return true instead of false and it worked fine. Weird.

```
    if (exec($this->convert_bin . " -version 2>&1")) {
      $this->EE->TMPL->log_item('**Thumber** Can\'t find ImageMagick on your server at ' . $this->convert_bin);
      return false;
    }
```

**Comment by malcolmwax** [comment]
Hi James,

If this amend worked for you go for it. The tests may not be perfect.

Thanks,
Malcolm
